apiVersion: apps/v1
kind: Deployment
metadata: 
  name: flaskapp-deployment
  labels:
    app: flaskapp
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: flaskapp
  template:
    metadata: 
      name: flaskapp-pod
      labels:
         app: flaskapp
    spec: 
      containers:
       - name: flaskapp-pod
         image : flaskapp
         ports: 
           - containerPort: 5000
         imagePullPolicy: Never
